services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.4
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - .docker/data:/var/lib/weaviate
    restart: unless-stopped

  text-spellcheck:
    container_name: text-spellcheck
    image: cr.weaviate.io/semitechnologies/text-spellcheck-model:pyspellchecker-en

  t2v-gpt4all:
    container_name: t2v-gpt4all
    image: cr.weaviate.io/semitechnologies/gpt4all-inference:all-MiniLM-L6-v2
