services:
  weaviate:
    container_name: weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.26.4
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - .docker/data:/var/lib/weaviate
    restart: unless-stopped
    # environment:
    #   GPT4ALL_INFERENCE_API: 'http://t2v-gpt4all:8080'
    #   SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
    #   OPENAI_APIKEY: $OPENAI_APIKEY
    #   QUERY_DEFAULTS_LIMIT: 25
    #   AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
    #   PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    #   DEFAULT_VECTORIZER_MODULE: 'text2vec-gpt4all'
    #   ENABLE_MODULES: 'text2vec-gpt4all,text-spellcheck,ref2vec-centroid,generative-openai'
    #   CLUSTER_HOSTNAME: 'node1'
    #   RAFT_ENABLE_ONE_NODE_RECOVERY: 'true'

  text-spellcheck:
    container_name: text-spellcheck
    image: cr.weaviate.io/semitechnologies/text-spellcheck-model:pyspellchecker-en

  t2v-gpt4all:
    container_name: t2v-gpt4all
    image: cr.weaviate.io/semitechnologies/gpt4all-inference:all-MiniLM-L6-v2
